[
    {"pile":"spadeFoundation","cards":[]},
    {"pile":"clubFoundation","cards":[]},
    {"pile":"heartFoundation","cards":[]},
    {"pile":"diamondFoundation","cards":[]},
    {"pile":"stock","cards":[
        {"name":"spade10","value":10,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"diamond3","value":3,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"club4","value":4,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"heart8","value":8,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"heart2","value":2,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"heart3","value":3,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"spade13","value":13,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"diamond8","value":8,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"spade8","value":8,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"spade1","value":1,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"heart1","value":1,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"club9","value":9,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"club6","value":6,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"club2","value":2,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"heart6","value":6,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"heart11","value":11,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"diamond12","value":12,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"diamond7","value":7,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"club12","value":12,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"club7","value":7,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"heart10","value":10,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"spade5","value":5,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"spade4","value":4,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"spade3","value":3,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false}
    ]},
    {"pile":"talon","cards":[]},
    {"pile":"tableau1","cards":[
        {"name":"club11","value":11,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":true}
    ]},
    {"pile":"tableau2","cards":[
        {"name":"spade9","value":9,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"heart4","value":4,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":true}
    ]},
    {"pile":"tableau3","cards":[
        {"name":"spade12","value":12,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"diamond13","value":13,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"spade11","value":11,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":true}
    ]},
    {"pile":"tableau4","cards":[
        {"name":"heart5","value":5,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"heart13","value":13,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"club5","value":5,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"diamond4","value":4,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":true}
    ]},
    {"pile":"tableau5","cards":[
        {"name":"spade2","value":2,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"heart12","value":12,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"club3","value":3,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"heart9","value":9,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":false},
        {"name":"diamond6","value":6,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":true}
    ]},
    {"pile":"tableau6","cards":[
        {"name":"diamond1","value":1,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"club1","value":1,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"diamond10","value":10,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"diamond11","value":11,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"diamond5","value":5,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"diamond9","value":9,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":true}
    ]},
    {"pile":"tableau7","cards":[
        {"name":"club10","value":10,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"spade6","value":6,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"diamond2","value":2,"suite":{"suite":"diamond","symbol":"♦","color":"red"},"face":false},
        {"name":"club8","value":8,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"spade7","value":7,"suite":{"suite":"spade","symbol":"♠","color":"black"},"face":false},
        {"name":"club13","value":13,"suite":{"suite":"club","symbol":"♣","color":"black"},"face":false},
        {"name":"heart7","value":7,"suite":{"suite":"heart","symbol":"♥","color":"red"},"face":true}
    ]}
]